
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anishmahto
 * Date: Aug 21, 2018
 * Purpose: this class is the page that expains the rules of Boggle to the user
 */
public class BoggleRules extends javax.swing.JFrame {

    /**
     * Creates new form Instructions
     */
    public BoggleRules() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubTitle1 = new javax.swing.JLabel();
        lblRule2 = new javax.swing.JLabel();
        lblRule1 = new javax.swing.JLabel();
        lblRule3 = new javax.swing.JLabel();
        lblRule5 = new javax.swing.JLabel();
        lblRule4 = new javax.swing.JLabel();
        lblRule7 = new javax.swing.JLabel();
        lblRule8 = new javax.swing.JLabel();
        lblRule9 = new javax.swing.JLabel();
        lblPatternImg1 = new javax.swing.JLabel();
        lblPatternImg2 = new javax.swing.JLabel();
        lblRule6 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnGuiInstructions = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setToolTipText("");
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1043, 500));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1043, 741));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setForeground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMaximumSize(new java.awt.Dimension(1043, 741));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1043, 1000));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        lblTitle.setText("Boggle Rules");

        lblSubTitle1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSubTitle1.setText("How to Play Boggle:");

        lblRule2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule2.setText("<HTML>- The player is given 3 minutes to make as many <b>unique</b> words as possible<HTML>");

        lblRule1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule1.setText("<HTML>Boggle is a word game that takes place on a 4x4 grid of letters. The purpose of the game is maximize your score by trying to make as many words as possible using the letters on the grid. The specific rules are as follows:<HTML>");

        lblRule3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule3.setText("<HTML>- The words the user makes <b>must</b> be 3 letters or longer<HTML>");

        lblRule5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule5.setText("<HTML>- Start at some cell in the grid; the letter on this cell is the first letter of the word<HTML>");

        lblRule4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule4.setText("<HTML>- A word made on the grid is considered <i>valid</i> if and only if you can do the following: <HTML>");

        lblRule7.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule7.setText("<HTML>- Move to any cell that is adjacent or diagonal to the current cell that has not been visited yet while making your current string, and add that letter to your current string<HTML>");

        lblRule8.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule8.setText("<HTML>- If the current string is has more than 3 letters and is an English word, it is considered valid.<HTML>");

        lblRule9.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule9.setText("<HTML>Example Valid Patterns On Right ----> <HTML>");

        lblPatternImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bogglePattern1.jpg"))); // NOI18N

        lblPatternImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bogglePattern2.jpg"))); // NOI18N

        lblRule6.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lblRule6.setText("<HTML><b>NOTE</b>: The letter 'Q' in this game represents 'Qu', as the letter Q alone can never be used<HTML>");

        btnHome.setBackground(new java.awt.Color(52, 73, 94));
        btnHome.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnGuiInstructions.setBackground(new java.awt.Color(52, 73, 94));
        btnGuiInstructions.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGuiInstructions.setForeground(new java.awt.Color(255, 255, 255));
        btnGuiInstructions.setText("GUI Instructions");
        btnGuiInstructions.setBorder(null);
        btnGuiInstructions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuiInstructionsMouseClicked(evt);
            }
        });

        btnPlay.setBackground(new java.awt.Color(46, 204, 113));
        btnPlay.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play");
        btnPlay.setBorder(null);
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRule1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRule2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRule3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRule4, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblRule5, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblRule7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(lblRule6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                                        .addComponent(lblRule8, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuiInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblRule9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatternImg1)
                    .addComponent(lblPatternImg2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(140, 140, 140))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(10, 10, 10)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblSubTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRule1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRule2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(lblPatternImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblRule6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblRule9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuiInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPatternImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlBackground);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void close () {
        //this close method segment is something I learned from ICS 3UE (Mr. Leduchowiski's class) for the final project in July, and am reusing it here.
        //the method helps me close the current page after opening another page
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        //create instance of the HomePage JFrame
        HomePage homePage = new HomePage();
        //set the instantiated JFrame as visible
        homePage.setVisible(true);
        //close the current JFrame
        close();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnGuiInstructionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuiInstructionsMouseClicked
        //create instance of the GuiInstrucitions JFrame
        GuiInstructions guiInstructionsPage = new GuiInstructions();
        //set the instantiated JFrame as visible
        guiInstructionsPage.setVisible(true);
        //close the current JFrame
        close();
    }//GEN-LAST:event_btnGuiInstructionsMouseClicked

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        //create instance of the BoggleGame JFrame
        BoggleGame boggleGamePage = new BoggleGame();
        //set the instantiated JFrame as visible
        boggleGamePage.setVisible(true);
        //cloes the current JFrame
        close();
    }//GEN-LAST:event_btnPlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoggleRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoggleRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoggleRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoggleRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoggleRules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiInstructions;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPlay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatternImg1;
    private javax.swing.JLabel lblPatternImg2;
    private javax.swing.JLabel lblRule1;
    private javax.swing.JLabel lblRule2;
    private javax.swing.JLabel lblRule3;
    private javax.swing.JLabel lblRule4;
    private javax.swing.JLabel lblRule5;
    private javax.swing.JLabel lblRule6;
    private javax.swing.JLabel lblRule7;
    private javax.swing.JLabel lblRule8;
    private javax.swing.JLabel lblRule9;
    private javax.swing.JLabel lblSubTitle1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
