
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anishmahto
 * Date: Aug 21, 2018
 * Purpose: This class contains the home/splash page the user is first greeted with
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnInstructions1 = new javax.swing.JButton();
        lblBackgroundImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1378, 751));
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1043, 891));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1043, 851));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1723, 851));
        pnlBackground.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("By Anish Mahto, for Mr. Jeg's ICS 4UE class");
        pnlBackground.add(jLabel1);
        jLabel1.setBounds(271, 635, 400, 50);

        lblTitle.setFont(new java.awt.Font("Arial", 1, 128)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Boggle!");
        pnlBackground.add(lblTitle);
        lblTitle.setBounds(470, 240, 500, 150);

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        pnlBackground.add(btnExit);
        btnExit.setBounds(590, 510, 240, 50);

        btnPlay.setBackground(new java.awt.Color(46, 204, 113));
        btnPlay.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play");
        btnPlay.setBorder(null);
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        pnlBackground.add(btnPlay);
        btnPlay.setBounds(410, 420, 240, 50);

        btnInstructions1.setBackground(new java.awt.Color(46, 204, 113));
        btnInstructions1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnInstructions1.setForeground(new java.awt.Color(255, 255, 255));
        btnInstructions1.setText("Instructions");
        btnInstructions1.setBorder(null);
        btnInstructions1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInstructions1MouseClicked(evt);
            }
        });
        pnlBackground.add(btnInstructions1);
        btnInstructions1.setBounds(770, 420, 240, 50);

        lblBackgroundImg.setForeground(new java.awt.Color(255, 255, 255));
        lblBackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boggleBackground.jpg"))); // NOI18N
        lblBackgroundImg.setText("srdsfrtwr");
        lblBackgroundImg.setPreferredSize(new java.awt.Dimension(1990, 851));
        pnlBackground.add(lblBackgroundImg);
        lblBackgroundImg.setBounds(-10, -10, 1730, 910);

        jScrollPane1.setViewportView(pnlBackground);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(-17, 0, 1720, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        //create instance of the BoggleGame JFrame
        BoggleGame boggleGamePage = new BoggleGame();
        //set the instantiated JFrame as visible
        boggleGamePage.setVisible(true);
        //close the current JFrame
        close();
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        //if the exit button is clicked, end program execution
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnInstructions1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstructions1MouseClicked
        //create instance of the BoggleRules JFrame
        BoggleRules boggleRulesPage = new BoggleRules();
        //set the instantiated JFrame as visible
        boggleRulesPage.setVisible (true);
        //close the current JFrame
        close();
    }//GEN-LAST:event_btnInstructions1MouseClicked

    public void close () {
        //this close method segment is something I learned from ICS 3UE (Mr. Leduchowiski's class) for the final project in July, and am reusing it here.
        //the method helps me close the current page after opening another page
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInstructions1;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackgroundImg;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
